name: Delete-Old-Branches

on: 
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '1 0 1 1-12 *'

jobs:
  delete-old-branches:
    name: Delete old branches
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: mihaidam/city-sniffer-dashboard@v1
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          date: '1 month ago'
          dry_run: true
          delete_tags: true
          minimum_tags: 5
          extra_protected_branch_regex: ^(foo|bar)$
